spring.datasource.url=jdbc:postgresql://localhost:5432/ticketdb
spring.datasource.username=ticket
spring.datasource.password=ticket_secret
spring.jpa.hibernate.ddl-auto=update

# Keycloak realm 'ticket' on localhost
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/ticket/protocol/openid-connect/certs

server.port=8085
